version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\peter-wangxu\goock

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go build -v

build_script:
  - for /f "" %%G in ('go list ./... ^| find /i /v "vendor/"') do @go vet %%G
  - for /f "" %%G in ('go list ./... ^| find /i /v "vendor/"') do @go test -v -race %%G