version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run:
          name: test
          command: |
            go build -v
            test $(gofmt -d $(find . -name '*.go' | grep -v 'vendor/') | wc -l) -eq 0
            go vet $(go list ./... | grep -v 'vendor/')
            go test -v -race $(go list ./... | grep -v 'vendor/')
            bash gen_cover.sh
            bash <(curl -s https://codecov.io/bash)